# Generated by Django 2.2.4 on 2020-01-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_text', models.DateField()),
                ('client_text', models.CharField(max_length=50)),
                ('project_text', models.CharField(max_length=50)),
                ('project_code_text', models.CharField(max_length=10)),
                ('task_text', models.CharField(max_length=50)),
                ('notes_text', models.CharField(max_length=200)),
                ('hours_text', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billable_text', models.CharField(max_length=10)),
                ('invoiced_text', models.CharField(max_length=10)),
                ('approved_text', models.CharField(max_length=10, null=True)),
                ('first_name_text', models.CharField(max_length=50)),
                ('last_name_text', models.CharField(max_length=50)),
                ('roles_text', models.CharField(max_length=20)),
                ('employee_text', models.CharField(max_length=10)),
                ('billable_rate_text', models.CharField(max_length=10)),
                ('billable_amount_decimal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_rate_text', models.CharField(max_length=20)),
                ('cost_amount_decimal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_text', models.CharField(max_length=50)),
                ('external_reference_text', models.CharField(max_length=200)),
            ],
        ),
    ]
