# Generated by Django 2.2.4 on 2020-01-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='hours_text',
            new_name='hours_decimal',
        ),
    ]
